name: Lint PR title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            BREAKING
            [unstable] BREAKING
            deprecation
            [unstable] deprecation
            feat
            release
            fix
            docs
            refactor
            perf
            test
            ci
            chore
            revert
          subjectPattern: '^[A-Z].+$'
          subjectPatternError: |
            The subject "{subject}" in the pull request title "{title}"
            must start with an uppercase letter.
          requireScope: true
          # This should be kept up-to-date with the current packages list
          scopes: |
            reactive(/unstable)?
